Sidecars
Olivier-St-Pierre/helm-charts pull request #1
Opened 2021-11-19 22:40 UTC by Olivier-St-Pierre

2021-11-22 18:21 UTC, devodev requested changes
Please document possible values in values files.

2021-11-22 18:21 UTC, devodev commented on charts/redis/values.yaml
> +sidecars: []
We should document the possible fields in a comment, similar to above.

2021-11-22 18:21 UTC, devodev commented on charts/redis-cluster/values.yaml
> +sidecars: []
same as my other comment about documentation.

2021-11-24 13:28 UTC, devodev approved these changes
LGTM :)

2021-11-25 00:38 UTC, Olivier-St-Pierre commented
Do I wait for a 2nd review or I merge?

2021-11-29 22:46 UTC, merged